"""add language to posts

Revision ID: 768e73d8e054
Revises: 2d7f4b704c35
Create Date: 2022-08-26 22:35:16.369003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768e73d8e054'
down_revision = '2d7f4b704c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
